services:
  backend:
    build: .
    command: uvicorn core.asgi:application --host 0.0.0.0 --port 8000 --lifespan off
    environment:
      CELERY_BROKER_URL: redis://host.docker.internal:6379/0
      CELERY_RESULT_BACKEND: redis://host.docker.internal:6379/1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/app
      - ./staticfiles:/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - redis
    restart: always

  celery-worker:
    build: .
    command: celery -A core worker --loglevel=info -c 4  # Adjust the number of workers (4 in this example)
    environment:
      CELERY_BROKER_URL: redis://host.docker.internal:6379/0
      CELERY_RESULT_BACKEND: redis://host.docker.internal:6379/1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/app
    depends_on:
      - backend
      - redis
    restart: always


  celery-beat:
    build: .
    command: celery -A core beat -l info -S django
    environment:
      CELERY_BROKER_URL: redis://host.docker.internal:6379/0
      CELERY_RESULT_BACKEND: redis://host.docker.internal:6379/1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/app
    depends_on:
      - backend
      - celery-worker
      - redis
    restart: always

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always

  onlogs:
    image: devforth/onlogs
    restart: always
    environment:
      - ADMIN_USERNAME=${ONLOGS_ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ONLOGS_ADMIN_PASSWORD}
      - PORT=8798
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers # if you want to delete duplicating logs from docker
      - onlogs-volume:/leveldb
    ports:
      - "8798:8798"

volumes:
  onlogs-volume:
